baseURL = "http://talkto.nyc"
languageCode = "en-us"
title = "Talk to NYC"
theme = "gohugo-theme-ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 15 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "UA-104381257-1"
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  hero = "It's time to forge stronger connections between NYC citizens and city decision makers."
  description = "Talk to NYC is working to introduce tools that will forge a stronger connection between NYC citizens and city decision makers."
  facebook = ""
  twitter = "https://twitter.com/TalktoNYC"
  instagram = "https://instagram.com/TalktoNYC"
  youtube = ""

  background_color_class = "bg-white"
  featured_image = "/img/hero-nyc.jpg"

# Primary menu displays in header
[[menu.primary]]
    name = "Take a Survey"
    weight = 6
    identifier = "take"
    url = "/survey"
[[menu.primary]]
    name = "Make a Survey"
    weight = 5
    identifier = "make"
    url = "/learn/make-survey"
[[menu.primary]]
    name = "Learn"
    weight = 3
    identifier = "learn"
    url = "/learn/"
[[menu.primary]]
    name = "Results"
    weight = 3
    identifier = "results"
    url = "/results/"

# Learn menu in the footer
[[menu.learn]]
    name = "How do I take a survey?"
    weight = 1
    identifier = "take-survey"
    url = "/learn/take-survey"
[[menu.learn]]
    name = "How do I interpret results?"
    weight = 2
    identifier = "learn-results"
    url = "/learn/interpret-results"
[[menu.learn]]
    name = "What is Pol.is?"
    weight = 1
    identifier = "learn-polis"
    url = "/learn/polis"


# Survey menu
[[menu.survey]]
    name = "Take"
    weight = 1
    identifier = "take-survey"
    url = "/survey"
[[menu.survey]]
    name = "Make"
    weight = 2
    identifier = "make-survey"
    url = "/learn/make-survey"


[[menu.privacy]]
    name = "Team"
    weight = 3
    identifier = "about"
    url = "/about/"
[[menu.privacy]]
    name = "Privacy"
    weight = 4
    identifier = "privacy"
    url = "/privacy/"
[[menu.privacy]]
    name = "Site Use Guidelines"
    weight = 5
    url = "/site-use/"
