baseURL = "http://concerned-smoke.surge.sh"
languageCode = "en-us"
title = "Talk to NYC"
theme = "gohugo-theme-ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  hero = "A platform to forge stronger connections between NYC citizens and city decision makers."
  description = "Talk to NYC is working to introduce tools that will forge a stronger connection between NYC citizens and city decision makers."
  facebook = ""
  twitter = "https://twitter.com/TalktoNYC"
  instagram = "https://instagram.com/TalktoNYC"
  youtube = ""

  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/img/hero-nyc-at-night.jpg"

# Primary menu displays in header
[[menu.primary]]
    name = "Take a Survey"
    weight = 1
    identifier = "take"
    url = "/survey/take"
[[menu.primary]]
    name = "Make a Survey"
    weight = 2
    identifier = "make"
    url = "/survey/make"
[[menu.primary]]
    name = "Learn"
    weight = 3
    identifier = "learn"
    url = "/learn/"
[[menu.primary]]
    name = "Results"
    weight = 3
    identifier = "results"
    url = "/results/"
[[menu.primary]]
    name = "About"
    weight = 4
    identifier = "about"
    url = "/about/"


# Learn menu in the footer
[[menu.learn]]
    name = "How to interpret results?"
    weight = 2
    identifier = "learn-results"
    url = "/learn/interpret-results"
[[menu.learn]]
    name = "What is Pol.is?"
    weight = 1
    identifier = "learn-polis"
    url = "/learn/polis"


# Survey menu
[[menu.survey]]
    name = "Take"
    weight = 1
    identifier = "learn-results"
    url = "/survey"
[[menu.survey]]
    name = "Make"
    weight = 2
    identifier = "learn-polis"
    url = "/learn/make-survey"
[[menu.survey]]
    name = "Candidate Forums"
    weight = 3
    identifier = "learn-take"
    url = "/survey"


[[menu.privacy]]
    name = "Privacy"
    weight = 4
    identifier = "privacy"
    url = "/privacy/"
[[menu.privacy]]
    name = "Site Use Guidelines"
    weight = 5
    url = "/site-use/"
[[menu.privacy]]
    name = "Contact"
    weight = 5
    url = "/contact/"
